apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: airflow
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: airflow
    spec:
      containers:
        - args:
            - sleep
            - infinity
          env:
            - name: AIRFLOW_HOME
              value: /opt/airflow
            - name: AIRFLOW__CORE__FERNET_KEY
              value: PeszOD9t6wKNdNONTGh-k4qsYbsGHQ8CSqTQZlqPCDk=
          image: airflow
          name: airflow
          ports:
            - containerPort: 8500
          resources: {}
          volumeMounts:
            - mountPath: /opt/airflow/dags
              name: airflow-claim0
      restartPolicy: Always
      volumes:
        - name: airflow-claim0
          persistentVolumeClaim:
            claimName: airflow-claim0
status: {}
