apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db2-datalab
  name: db2-datalab
spec:
  ports:
    - name: "50000"
      port: 50000
      targetPort: 50000
  selector:
    io.kompose.service: db2-datalab
status:
  loadBalancer: {}
