apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-datalab
  name: grafana-datalab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana-datalab
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/datalab-network: "true"
        io.kompose.service: grafana-datalab
    spec:
      containers:
        - image: docker.io/grafana/grafana
          name: grafana-datalab
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-datalab-claim0
      hostname: grafana-datalab
      restartPolicy: Always
      volumes:
        - name: grafana-datalab-claim0
          persistentVolumeClaim:
            claimName: grafana-datalab-claim0
status: {}
