apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: minio-datalab
  name: minio-datalab
spec:
  ports:
    - name: "9001"
      port: 9001
      targetPort: 9000
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: minio-datalab
status:
  loadBalancer: {}
