apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: minio-datalab
  name: minio-datalab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio-datalab
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/datalab-network: "true"
        io.kompose.service: minio-datalab
    spec:
      containers:
        - args:
            - server
            - /data
            - --console-address
            - :9090
          env:
            - name: MINIO_ROOT_PASSWORD
              value: idontwanttosearch
            - name: MINIO_ROOT_USER
              value: batman
          image: quay.io/minio/minio
          name: minio-datalab
          ports:
            - containerPort: 9000
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: minio-datalab-claim0
      hostname: minio-datalab
      restartPolicy: Always
      volumes:
        - name: minio-datalab-claim0
          persistentVolumeClaim:
            claimName: minio-datalab-claim0
status: {}
