apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: promserver-datalab
  name: promserver-datalab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promserver-datalab
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert -c
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/datalab-network: "true"
        io.kompose.service: promserver-datalab
    spec:
      containers:
        - image: docker.io/prom/prometheus
          name: promserver-datalab
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /etc/prometheus
              name: promserver-datalab-claim0
      hostname: promserver-datalab
      restartPolicy: Always
      volumes:
        - name: promserver-datalab-claim0
          persistentVolumeClaim:
            claimName: promserver-datalab-claim0
status: {}
