apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker
  name: spark-worker
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "8082"
      port: 8082
      targetPort: 8081
    - name: "8083"
      port: 8083
      targetPort: 8081
    - name: "8084"
      port: 8084
      targetPort: 8081
    - name: "8085"
      port: 8085
      targetPort: 8081
  selector:
    io.kompose.service: spark-worker
status:
  loadBalancer: {}
