apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  ports:
    - name: "4040"
      port: 4040
      targetPort: 4040
    - name: "7077"
      port: 7077
      targetPort: 7077
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "18080"
      port: 18080
      targetPort: 18080
  selector:
    io.kompose.service: spark-master
status:
  loadBalancer: {}
